// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHaAvU_BhzWZE0k5BK4fLEoE-31RtW3no',
    appId: '1:392286040873:web:60ac05b0eac21aaee3bd38',
    messagingSenderId: '392286040873',
    projectId: 'joinup-c792e',
    authDomain: 'joinup-c792e.firebaseapp.com',
    storageBucket: 'joinup-c792e.firebasestorage.app',
    measurementId: 'G-ZNEBNXCGPC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBzpHmbf5xchUrlpjIFcHRK6NI2fjw2y4',
    appId: '1:392286040873:ios:24a74fa211562ecbe3bd38',
    messagingSenderId: '392286040873',
    projectId: 'joinup-c792e',
    storageBucket: 'joinup-c792e.firebasestorage.app',
    iosBundleId: 'com.example.joinUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBzpHmbf5xchUrlpjIFcHRK6NI2fjw2y4',
    appId: '1:392286040873:ios:24a74fa211562ecbe3bd38',
    messagingSenderId: '392286040873',
    projectId: 'joinup-c792e',
    storageBucket: 'joinup-c792e.firebasestorage.app',
    iosBundleId: 'com.example.joinUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHaAvU_BhzWZE0k5BK4fLEoE-31RtW3no',
    appId: '1:392286040873:web:01b57cbbfe8d47e5e3bd38',
    messagingSenderId: '392286040873',
    projectId: 'joinup-c792e',
    authDomain: 'joinup-c792e.firebaseapp.com',
    storageBucket: 'joinup-c792e.firebasestorage.app',
    measurementId: 'G-G77EEX26ZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUgE2x147nM6uwQVI3zGKTmboVQl6Hxz4',
    appId: '1:392286040873:android:e4a61053f94ecc17e3bd38',
    messagingSenderId: '392286040873',
    projectId: 'joinup-c792e',
    storageBucket: 'joinup-c792e.firebasestorage.app',
  );

}