name: join_up
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
intl: ^0.18.0

# Firebase paketleri (birbiriyle uyumlu)
firebase_core: ^2.32.0
firebase_auth: ^4.16.0
cloud_firestore: ^4.15.7

code_uml: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/palm-recognition.png
