intl:
  dependency: direct
  description:
    name: intl
    sha256: "3bc132a9dbce73a7e4a21a17d06e1878839ffbf975568bc875c60537824b0c4d"
    url: "https://pub.dev"
  source: hosted
  version: "0.18.1"

io:
  dependency: transitive
  description:
    name: io
    sha256: dfd5a80599cf0165756e3181807ed3e77daf6dd4137caaad72d0b7931597650b
    url: "https://pub.dev"
  source: hosted
  version: "1.0.5"

js:
  dependency: transitive
  description:
    name: js
    sha256: f2c445dce49627136094980615a031419f7f3eb393237e4ecd97ac15dea343f3
    url: "https://pub.dev"
  source: hosted
  version: "0.6.7"
