name: join_up
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  code_uml: ^1.0.2

  # Firebase paketleri (birbiriyle uyumlu)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: 5.6.7
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/palm-recognition.png
